from pathlib import Path
import torch


class Parameters:

    PATH_TO_MODELS = Path("models")
    MODELS_TO_DOWNLOAD = [
        "unsloth/Llama-3.1-8B-Instruct-bnb-4bit",  # Baseline
        "mlabonne/Meta-Llama-3.1-8B-Instruct-abliterated",  # Abliterated
    ]

    PATH_TO_DATASETS = Path("datasets")
    PATH_TO_DATASETS_DOWNLOADS = PATH_TO_DATASETS / "downloaded"
    PATH_TO_DATASETS_SPLITS = PATH_TO_DATASETS / "splits"
    PATH_TO_DATASETS_LABELS = PATH_TO_DATASETS / "splits_with_labels"

    PATH_TO_CHECKPOINTS = Path("checkpoints")

    MODEL_NICKNAME = "llama"
    MODEL_NAME_BASELINE = "Llama-3.1-8B-Instruct-bnb-4bit"
    MODEL_NAME_ABLITERATED = "Meta-Llama-3.1-8B-Instruct-abliterated"
    MODEL_NAME_JAILBREAK_PRE_TAR = f"{MODEL_NAME_BASELINE}-jailbreak-pre-tar"
    MODEL_NAME_JAILBREAK_POST_TAR = f"{MODEL_NAME_BASELINE}-jailbreak-post-tar"
    MODEL_NAME_TAR = f"{MODEL_NAME_BASELINE}-tar"

    SEED = 3407
    DTYPE = torch.bfloat16
    MAX_SEQ_LENGTH = 1024
    MIN_NEW_TOKENS = 50
    MAX_NEW_TOKENS = 600
    TARGET_LAYER_INDEX = 20
    LOAD_IN_4_BITS = True

    STEERING_FEATURES_INDICES = [12227, 20768, 22358, 6953, 296, 4420, 19243, 6886, 26576, 25406, 28487, 23835, 19544, 23172, 6308, 3606]

    NB_SAMPLES_TRAIN = 1200
    NB_TRAIN_TAR = 1200
    NB_TRAIN_ADVERSARIAL = 1200
    NB_TEST = 200

    # ADVERSARIAL_FINE_TUNING (AFT)
    BATCH_SIZE_AFT = 4
    GRADIENT_ACCUMULATION_STEPS_AFT = 4
    LEARNING_RATE_AFT = 2e-4
    WARMUP_STEPS_AFT = 5
    NB_STEPS_AFT = 10
    OPTIM_AFT = "adamw_8bit"
    WEIGHT_DECAY_AFT = 0.01
    LR_SCHEDULER_TYPE_AFT = "linear"

    # TAMPER ATTACK RESISTANCE (TAR)
    BATCH_SIZE_TAR = 4
    GRADIENT_ACCUMULATION_STEPS_TAR = 8
    LEARNING_RATE_TAR = 2e-4
    WARMUP_STEPS_TAR = 10
    NB_STEPS_TAR = 60
    OPTIM_TAR = "adamw_8bit"
    LR_SCHEDULER_TYPE_TAR = "cosine"
    MAX_GRAD_NORM_TAR = 1.0
    LEARNING_RATE_INNER_TAR = 1e-2
    ALPHA_TAR = 0.5
    BETA_TAR = 5.0
    GAMMA_TAR = 1.0
    TAMPERING_THRESHOLD_TAR = 5.0
    PROBABILITY_SYSTEM_PROMPT_TAR = 0.5
    NB_INNER_STEPS_MIN_TAR = 30
    NB_INNER_STEPS_MAX_TAR = 50
